USE vbh_crm;
SET sql_mode ='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

delete from act_ru_task;
delete from act_hi_actinst;
delete from act_hi_identitylink;
delete from act_hi_procinst;
delete from act_hi_taskinst;
delete from act_hi_varinst;
delete from act_ru_identitylink;
delete from act_ru_variable;
delete from act_ru_execution;
delete from sys_fhlog;
delete from sys_fhsms;
delete from sys_user where username not in ('admin','citycomp5');
delete from vbh_crm_card_voucher_t;
delete from vbh_crm_chat_t;
delete from vbh_crm_contacter_t;
delete from vbh_crm_contract_commission_rate_t;
delete from vbh_crm_contract_file_t;
delete from vbh_crm_contract_pay_plan_t;
delete from vbh_crm_contract_pay_t;
delete from vbh_crm_contract_t;
delete from vbh_crm_customer_order_t;
delete from vbh_crm_customer_t;
delete from vbh_crm_distributor_check_detail_t;
delete from vbh_crm_distributor_check_t;
delete from vbh_crm_distributor_profit_pay_detail_t;
delete from vbh_crm_distributor_profit_pay_t;
delete from vbh_crm_distributor_profit_rule_t where distributor_profit_rule_id <> '3c4d268954e046e2a5aec5d14d3827e9';
delete from vbh_crm_distributor_profit_rule_detail_t  where distributor_profit_rule_id <> '3c4d268954e046e2a5aec5d14d3827e9';
delete from vbh_crm_distributor_t where user_name not in ('citycomp5') or user_name is null;
delete from vbh_crm_file_t;
delete from vbh_crm_leave_t;
delete from vbh_crm_news_read_t;
delete from vbh_crm_news_t;
delete from vbh_crm_payee_t;
delete from vbh_crm_permission_area_t;
delete from vbh_crm_record_update_log_t;
update vbh_crm_serial_number_t set current_serial_number = '0001';
delete from vbh_crm_user_source_t;
delete from vbh_crm_user_t where user_name not in ('admin','citycomp5');
delete from vbh_crm_workflow_doc_num;
delete from vbh_crm_workflow_log_t;
commit;

